### ISSUE TITLE
FEATURE: Slug / routing

### ISSUE THREAD

**Issue by okmiim** [lochmueller/calendarize#540]
# Feature: Slug
I plan to implement a new slug generation.
**Further feedback and ideas are welcome.**

The idea is to generate the slug in the indexing process.
For this the resulting slug consists out of multiple parts.   
`{1:recordSlug}-{2?:indexSuffix}-{3?:regular-core-conflict-counter}`

1. Identifyer of the record
    - **SpeakingUrlInterface**
    - **Slug field** in the model (fallback)
    - **uniqueRegisterKey-UID** (fallback)

2. Suffix for each index (only for multiple occurrence)
    - **date**

3. Counting suffix with conflict counter (optional)
    - Add suffix if slug is already in use, e.g. "/mytitle-1"
    - this needs to be done directly before inserting to prevent duplicates

The last step ensures that the slugs are unique.

## Examples

- Single occurrence (e.g. slug field `spacex-falcon-9-crew-2`): 
    - `spacex-falcon-9-crew-2`

- Multiple occurrences (e.g. slug field `weekly-recap`)
    - `weekly-recap-210402`
    - `weekly-recap-210416`

- Already in use (e.g. `winter-holiday`)
    - `winter-holiday-2`

- Custom event (`party`, uid=321) without slug/SpeakingUrlInterface:
    - `party-321`

## Subtasks

- [x] Implement slug generation (#541, daeefc3062e36696fd84207558847f9cd1e07167)
- [x] Add / Update routeEnhancers (#541, b7a8c2832636ae422bb6cacc0af12a2082cf84b9)
- [x] Implement Slug for Event-Model (#550)
- [x] UpgradeWizard to generate Slugs for existing Events/Configurations (#550)
- [ ] Add documentation for custom events
- [x] Deprecate EventMapper (#550)

## Open points

- Extensibility? If yes, how to keep achieve this? (PSR-14 Events, as a service, ???)
- ~~Slug field? Allow other names than `slug` or `path_segment`?~~ -> Use existing interface, since no uniques is required
- ~~Deprecate (/remove) the old interfaces / EventMapper?~~

Related #405

---
## Old version

> `{1:modelIdentifier}-{2:recordSlug}-{3?:indexSuffix}`
> 
> 1. Unique identifyer for the event model e.g. **`uniqueRegisterKey`**
>     - Dynamic with AspectMapper (or static at generation time)
> 
> 2. Unique identifyer of the record (must be unique inside event model)
>     - **Slug field** in the model (preferred)
>     - **UID** (of the event record, not index) + `SpeakingUrlInterface` (fallback)
>     - **UID** (fallback)
> 
> 3. Suffix for each index (multiple occurrence)
>     - **date**
>     - **counting suffix**
> 
> Due the combination of these parts, the resulting slug should be unqiue.
> So there is no need to query the existing index.

**Comment by lochmueller** [comment]
Hey @okmiim 
that sounds great. Some thoughts related to this topic.
The field is already part of the DB. So feel free to use the slug field: https://github.com/lochmueller/calendarize/blob/master/Classes/Domain/Model/Index.php#L114
I suggest this structure `{1:recordSlug}-{2?:indexSuffix}-{3?:regular-core-conflict-counter}`. I think we need the event model identifier not and should keep the "conflict mode" of the slug generation in mind. The "indexSuffix" should be "smart". Perhaps we could leave the part empty, if the event do not use recurrence/frequencies, otherwise date only (with allday set) and in the fallback incl. the time.

Related to the subtask. I think "IndexPreparationService" is to early. If we want to use the conflict behavior of the TYPO3 core, we have to generate the slug directly before the persist process.
Extensibility: Good option. We could use a simple interface (like the speaking URL interface). The generation process itself could use PSR-14 events (but not necessary in the first step). The slug field in the index is fixed "slug" the slug field in the event structure should be part of the interface or configurable via event registration?!
Deprecation: I suggest to keep the old structure, but deprecated the functions and trigger deprecated errors like suggested by the core: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Deprecation/Index.html#deprecate-functions-in-extensions

Thanks for pushing this idea forward. Would be cool to get a "real slug" field in the index. This will reduce the complexity in the link building and resolving process (and move this complexity to the slug generation; But this is better).

Regards,
Tim

**Comment by okmiim** [comment]
Hi,
I implemented a working prototype 73b8667 with the "conflict mode".

Since we need no uniquess for the `recordSlug`, the `SpeakingUrlInterface` is enough and we need no additional interface.
However the nameing does not fit that well anymore.

This way of implementing has a higher database overhead and need to insert each record seperately.
Also the needed compare (line 209) does not recognize change in slug (the check is currently almost useless, due to `tstamp`).

I think there should still a slug field inside Event, so that the base part is not as volitile.

**Comment by lochmueller** [comment]
Hey @okmiim great first steps. I also like the idea to add also the slug field to the event table (the editor get an option to edit the real base for the index generation).

"This way of implementing has a higher database overhead and needs to insert each record seperately." -> since is not so important. But we should drop the tstamp field in the compare process so the index is not calculated again and again on editor workings...

Thanks for the progress.

Regards,
Tim
