### ISSUE TITLE
TYPO3 v12 support

### ISSUE THREAD

**Issue by zobnov** [lochmueller/calendarize#734]
Any plans to update the cms-core version so that the extension could be installed with composer on Typo3 12?

Below is my current output with error for reference:
——
Problem 1
     - lochmueller/calendarize[12.4.0, ..., 12.4.4] require typo3/cms-core ^10.4||^11.5 -> found typo3/cms-core[v10.4.0, ..., v10.4.34, v11.5.0, ..., v11.5.22] but it conflicts with your root composer.json require (^12).

**Comment by lochmueller** [comment]
Yes... but I think it is not directly on the agenda in the next weeks, because EXT:autoloader and EXT:calendarize must be compatible. I will check this in the next weeks and also check, if this could be part of some integration projects...

**Comment by zobnov** [comment]
@lochmueller thank you! Any suggestions on how could I install it today? I guess I could try changing the version in the composer file somewhere manually. Or maybe I could install the development version?

**Comment by lochmueller** [comment]
Hey @zobnov 
there is no dev version that is compatible. You can fork the repository, change the composer.json to fit qour requirements and install from your repository (just add your repo to your compoaser.json, you do not need change the package name). If you fix things, you could do this directly in your repository. If the changes are good, we cann merge this changes via pull requests back to the main repo.
Regards,
Tim

**Comment by zobnov** [comment]
Sounds good, I’ll try this out and will let you know. Thank you.

**Comment by okmiim** [comment]
A list of things to be check and migrated (probably incomplete):

- [ ] [Breaking: #96287 - Doctrine DBAL v3](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96287-DoctrineDBALv3.html)
- [ ] UriBuilder (AbstractActionViewHelper, AbstractLinkViewHelper)
- [ ] [Breaking: #97926 - Extbase QuerySettings methods removed](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97926-ExtbaseQuerySettingsMethodsRemoved.html)
- [ ] CmsLayout [Breaking: #98375 - Removed hooks in Page Module](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98375-RemovedHooksInPageModule.html)
- [ ] Check NextEventsDataProvider [Breaking: #98377 - Fluid StandaloneView does not create an Extbase Request anymore](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98377-FluidStandaloneViewDoesNotCreateAnExtbaseRequestAnymore.html)
- [ ] AbstractCompatibilityController
- [ ] CalMigration

Future when dropping v11 support
- [ ] [Breaking: #98443 - Extension recordlist merged into backend](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98443-ExtensionRecordlistMergedIntoBackend.html)
- [ ] [Deprecate QueryBuilder::execute()](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-96972-DeprecateQueryBuilderexecute.html)

**Comment by lochmueller** [comment]
Hey @okmiim 
Hey @zobnov 

Sebastian Fischer is currently prepare a v12 compatible version. Please check the forks to get insides of his work. Hey also decouple the extension from EXT:autoloader. He will work a few days and will send a pull request.

I suggest to wait for his work and check, if there are open points after the check/merge.

Regards,
Tim

**Comment by lochmueller** [comment]
@garbast FYI

**Comment by sandrotanner** [comment]
A lot of works has been going on in the mentioned forks ( https://github.com/lochmueller/calendarize and https://github.com/garbast/calendarize_pages ), thanks a lot @garbast  :pray:. The have been inactive for about a month now though so I wanted to ask: Do they need more work? Or is it practically ready and we can help with testing?

**Comment by garbast** [comment]
Hi. Sorry for the stale development, but i was quite busy with the project, where i use calendarize in.

In general the work is done. There are some things (the backend modul) that need some love, but in general i'm quite happy with the state.

**Comment by sandrotanner** [comment]
Cool, no worries.  Thank you!

**Comment by lochmueller** [comment]
Hey @romyschmidt 

Still the same. Currently, the v12 branch is not mergeable https://github.com/lochmueller/calendarize/pull/755 
if the branch is mergeable and we get some feedback, we will merge this and finish the backend module.
Feel free to check, why the PR could not merged and send some Feedback if there are any problems with this fork.

Regards,
Tim

**Comment by okmiim** [comment]
Known tasks/problems regarding TYPO3 v12


- [ ] [TASK] Flexform migration wizard: since each switchableControllerAction is now its own plugin, a migration for the old plugin `Calendarize` `Calendar` is needed (see other extensions like news)
- [ ] [BUG] Fix functional test failing `FullReindexTest::testFindLiveIndexAfterIndexAVersion`, `FullReindexTest::testFindIndexRecordsAfterReindexing`, `BackendPreviewTest::testOutputOfLiveEvents`
- [ ] [DOCS] Update docs, e.g. `Getting Started --> Add a plugin`, `DeveloperManual --> Own events`
- [ ] [TASK] ICS/XML/Atom: the old method in the `AbstractCompatibilityController` is not working anymore
  - throw `PropagateResponseException` to stop layout --> "**hacky** & fast solution", problematic with multiple actions on the same page
  - add `pageType` with typoscript for each format -->breaking to previous version, I think "**cleaner**" solutions, needs more work
  - contact me (@okmiim) if you want to work for it, have some local "test variants"
- [ ] [TASK] `Register.php` --> determine what to do with it, maybe remove
- [ ] [TASK] Check and remove/replace `TSFE`
- [ ] [BUG] Configuration: after saving the (start) time '00:00' it is empty afterwards --> annoying since required field
- [ ] [TASK] Check/remove/test language fields in Configuration (not used anyways)
- [ ] [TASK] Inconsistent naming of plugin wizard (create)

And as always: more testing

**Comment by hannesbochmann** [comment]
Maybe the flexform migration can be done with EXT:mktools. I added recently a command to do the migration of plugins with switchable controller actions in a generic way. @see https://github.com/DMKEBUSINESSGMBH/typo3-mktools/blob/12.4/Documentation/Utilities/Extbase/Index.md

**Comment by hannesbochmann** [comment]
Here are some example commands for the migration:

bin/typo3 mktools:migrate-switchable-controller-actions --actions="Calendar->detail" --list-type=calendarize_calendar --new-list-type=calendarize_detail

bin/typo3 mktools:migrate-switchable-controller-actions --actions="Calendar->list" --list-type=calendarize_calendar --new-list-type=calendarize_list

This worked for me pretty well.

**Comment by hannesbochmann** [comment]
@okmiim Can you tell me what exactly doesn't work anymore in the old method in the AbstractCompatibilityController when it comes to the feed rendering? As far as I can see the main/only problem is the retrieval of the response body. Right now "$response->getBody()->getContents()" is used. As the response got written previously the stream pointer is at the end of the stream and getContents() will start to output from the end when no rewind is done before. The correct method to use should be "$response->getBody()->__toString()" which rewinds the stream beforehand. I can provide a MR with the changes if there is no other problem.

**Comment by hannesbochmann** [comment]
Besides that I just installed calendarize in a 12.4 project with a fairly complex setup and custom events. So far I didn't run into any problems besides those which are already fixed/known.

**Comment by okmiim** [comment]
@hannesbochmann 

Feeds: your are right with the feed contents - thank you

Regarding switchable controller actions: 
I would prefer to have a migration integrated into the extensions, since it has a better user experience and everybody needs to do this. Not everyone is such tech savvy as you.

**Comment by hannesbochmann** [comment]
Yeah, I completely understand that. I try to find some time to add the migration. Would you prefer a command or a update wizard?

**Comment by lochmueller** [comment]
Hey @okmiim ,
what do you think about a v12 release in the next days?! My plan is...
- Release a v12 version to get some progress/speed in the dev/feedback process (incl. v11 drop)
- Close all issues that are not related to the current version
Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue (thanks for all the work. The release is already there ;) )... there are two followups:
- https://github.com/lochmueller/calendarize/issues/792
- https://github.com/lochmueller/calendarize/issues/708

Feel free to create more issues for open stuff.
